# Version from: June 2020

version: "3.5"
services:
  scripts:
    build: scripts
    depends_on:
      - coordinator
    environment:
      - COORDINATOR_NODE=coordinator
    networks:
      - cluster

  coordinator: # first node
    image: neo4j:3.5
    ports:
      - 7474:7474  # HTTP
      - 7687:7687  # Bolt
    environment:
      - NEO4J_AUTH=none
    networks:
      - cluster
    volumes:
      - data:/data  # persistent; remove for ephemeral tasks


    # The Open-Source version of Neo4j does *not* support multiple nodes;
    # hence, we won't support clusters in this setup.


networks:
  cluster:
    name: cluster

volumes:
  data: {}
